version: "3.6"

networks:
  twitch:

services:  
  rabbitmq:
    image: masstransit/rabbitmq:latest
    networks:
     - twitch
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
    healthcheck:
        timeout: 5s
        interval: 5s
        retries: 10
        test:
          - "CMD"
          - "rabbitmqctl"
          - "status"
  redis:
      image: redis
      networks:
      - twitch
      ports:
        - "6379:6379"